### ISSUE TITLE
Sector Times 

### ISSUE THREAD

**Issue by AlesandroDeMoor** [FrostHexABG/TimingSystem#10]
Sector times would be a very useful event feature to add in a future update. In motorsports, tracks are usually split into sectors (usually, 3 or 4) and it helps the viewer measure the pace of each driver through a lap, especially during qualifying.

The way I picture this working is by being able to mark down an area using WorldEdit just like you would any other checkpoint, but a new "sector" option would grant the possibility to mark the end of a sector (the first sector checkpoint would be the end of S1, then S2, until the finish line which would serve as the end of the final sector). The difference between these and regular checkpoints is that during a heat (mostly in each round of qualifying), the best individual sector time would be displayed every time someone manages to beat the record time on a determined sector. This is very helpful for event hosts and spectators alike to focus on the action. 

Each sector would be displayed with its own isolated time, not by the accumulated time of the lap (so by the end, the sum of all sectors could add up to a hypothetical "ideal" lap).

**Comment by JustBru00** [comment]
This has been addressed in FrostHexABG/FrostHexUtils@dbbf60b20845e5c566e18166ccf9b9576b8dbb43
