### ISSUE TITLE
Heat could not start.

### ISSUE THREAD

**Issue by kennychen2009** [FrostHexABG/TimingSystem#5]
So we are running an event on Purpur-2165 (1.20.4). After finishing the first quali heat, we can't load the final heat.It says "heat could not be loaded" When we used /heat info R1Q1, It says R1Q1(Finished).

There were two rounds and two heats:

Round 1 Quali:
R1Q1
Round 2 Final:
R2F1

Result of "/heat info R1Q1" and The plugins we installed are down below.
<img width="1440" alt="image" src="https://github.com/JustBru00/TimingSystem/assets/57182271/28b3525c-cb3f-45de-b5cc-9baab280b14b">

Idk if it's a but or the problem of the server. Sorry for my horrible English and thanks for your help!

**Comment by M2B5** [comment]
Did you also finish the qualification round? 
/round finish

**Comment by JustBru00** [comment]
User has not answered question. Assume that issue was resolved.
